spring:
    profiles: default
    application:
        name: payments
eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry:localhost:1111}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
server:
    port: 9002

security:
  oauth2:
    resource:
      loadBalanced: true
      #userInfoUri: http://${proxy:localhost:4444}/auth_service/users/current #problem with load balanced userInfoUri
      userInfoUri: http://auth/users/current
      #userInfoUri: http://auth/hascode/user
    client:
      client-id: clientapp
      client-secret: 123456
      scope: read,write
      auto-approve-scopes: '.*'

ribbon:
  eureka:
    enabled: true